name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest version

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v4  # Updated version
        with:
          path: ./  # Change if your site is in "dist" or "public"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
