name: Use GitHub Secret

on: 
  push:
    branches:
      - main  # Runs when you push to main

jobs:
  create-config:
    runs-on: ubuntu-latest  # The VM GitHub uses

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls repo so we can modify files

      - name: Generate config file
        run: |
          cat <<EOF > config.json
          {
            "API_KEY": "${{ secrets.API_KEY }}",
            "API_URL": "${{ secrets.API_URL }}",
            "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}"
          }
          EOF
        shell: bash

      - name: Use Config File (Example)
        run: cat config.json  # This is just to test if it's generated. Remove in production.

      - name: Cleanup - Delete config file
        if: always()
        run: rm -f config.json
