name: Use GitHub Secret

on: 
  push:
    branches:
      - main  # Runs when you push to main

jobs:
  create-config:
    runs-on: ubuntu-latest  # The VM GitHub uses

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls repo so we can modify files

      - name: Generate config file
        run: |
          echo '{
            "API_KEY": "${{ secrets.API_KEY }}",
            "API_URL": "${{ secrets.API_URL }}",
            "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}"
          }' > config.json

      - name: Commit and push config file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Reset to match the remote repo (avoids conflicts)
          git fetch origin main
          git reset --hard origin/main

          # Add the config.json file
          git add config.json
          git commit -m "Generated config file with secret" || echo "No changes to commit"

          # Force push to prevent rejected updates
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git


      - name: Cleanup - Delete config file
        if: always()
        run: rm -f config.json